-- Diese Datei wird nicht mehr gebraucht: Die Beispiel-Struktur (Industrie
-- Maschinenbau, Hersteller HOSCH, ...) wird jetzt direkt in der Migration
-- supabase/migrations/20260716000000_phase2_kategorie_ebenen.sql angelegt.
-- Weitere Kategorien/Teile legst du am besten direkt in der App unter
-- "Kategorien & Teile" an (nur für Admin/Superadmin sichtbar).
